[package]
name = "graph-embed-rust"
version = "0.0.1"
edition = "2021"

[dependencies]
nalgebra = "0.29"
nalgebra-sparse = "0.5"
rand = "0.8.4"
rayon = "1.5.1"
#ndarray = { version = "0.15.4", features = ["rayon"] }
